version: '3.8'

services:
  laravel_franken:
    container_name: laravel_franken
    image: image_laravel_franken
    build: .
    ports:
      - "8009:80"
    env_file:
      - .env
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
