services:
  blog_api:
    container_name: blog_api
    image: image_blog_api
    build: .
    ports:
      - "8005:80"
    env_file:
      - .env
    networks:
      - my_network

  mysql_server:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my_network

  caddy:
    image: caddy:latest
    container_name: blog_api_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blog_api_network
    depends_on:
      - blog_api

networks:
  my_network:
    driver: bridge
  blog_api_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
