services:
  blog_api:
    container_name: blog_api
    image: image_blog_api
    build: .
    ports:
      - "8005:80"
    env_file:
      - .env
    networks:
      - blog_api_network

  caddy:
    image: caddy:latest
    container_name: blog_api_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blog_api_network
    depends_on:
      - blog_api

networks:
  blog_api_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
