services:
  blog_api:
    container_name: blog_api
    image: image_blog_api
    build: .
    ports:
      - "8005:80"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    external: true
